version: '2'

services:  
  # Define an InfluxDB service
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    #image: influxdb:latest
    # To uncomment and adapt for mounting volumes
    volumes:
        - D:/docker/data/influxdbv2:/root/.influxdbv2
    ports:
        - "8086:8086"
    restart: always
  grafana:
    image: grafana/grafana:latest
    #image: influxdb:latest
    # To uncomment and adapt for mounting volumes
    volumes:
        - D:/docker/data/grafana/data:/var/lib/grafana
    ports:
        - "3000:3000"
    depends_on:
        - influxdb
    restart: always