version: '2'

services:  
  # Define an InfluxDB service
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    #image: influxdb:latest
    # To uncomment and adapt for mounting volumes
    #volumes:
    #  - D:/docker/data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Chronograf service
  chronograf:
    image: chronograf
    # To uncomment and adapt for mounting volumes
    #volumes:
    #  - D:/docker/data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    depends_on:
    - influxdb
    environment:
    - INFLUXDB_URL=http://influxdb:8086